import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'nodejs'
export const maxDuration = 60

const SYSTEM = `You are an expert SVG diagram designer for enterprise SAP technology proposals. When given a description, generate a complete, self-contained SVG diagram.

RULES
- Return ONLY the SVG element. Start with <svg and end with </svg>. No markdown fences, no explanation, no text outside the SVG.
- Use viewBox with explicit width and height. Default: width="900" height="560" for landscape diagrams, width="700" height="960" for tall/portrait ones.
- Dark background (#0E1020). All text must be legible on dark.
- Gradient bar at the very top (y=0, height=3): linear gradient left-to-right #FFB87E -> #FF7E51 -> #B88A99 -> #6399F0.
- Color palette: accent orange #FF7E51, blue #6399F0, peach #FFA962, green #00a864, mauve #B88A99, warm #FFB87E.
- Use these fills at 10-15% opacity for box backgrounds, full opacity for labels and accents.
- fontFamily="Inter, sans-serif" for all text. Bold weight for titles and layer labels.
- Include a small footer text at the bottom: "Confidential. Generated by DXC Proposal Builder." in rgba(255,255,255,0.2), font-size 9.
- Make the diagram genuinely useful and information-dense. Label everything clearly. Use boxes, arrows, zones, and hierarchy to convey structure.`

export async function POST(req: NextRequest) {
  const apiKey = req.headers.get('x-api-key') || process.env.ANTHROPIC_API_KEY
  if (!apiKey) return NextResponse.json({ error: 'API key missing' }, { status: 401 })

  let body: { prompt: string }
  try { body = await req.json() } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }) }

  const { prompt } = body
  if (!prompt?.trim()) return NextResponse.json({ error: 'Prompt required' }, { status: 400 })

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 4096,
        system: SYSTEM,
        messages: [{ role: 'user', content: prompt }],
      }),
    })

    const data = await res.json()
    if (!res.ok) {
      const detail = data?.error?.message || JSON.stringify(data)
      return NextResponse.json({ error: `Anthropic ${res.status}: ${detail}` }, { status: res.status })
    }

    const block = Array.isArray(data?.content) ? data.content[0] : null
    const svg = block?.type === 'text' ? block.text.trim() : ''
    return NextResponse.json({ svg })
  } catch (err: unknown) {
    const msg = err instanceof Error ? `${err.name}: ${err.message}` : 'Generation failed'
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
