import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'

const SYSTEM = `You are an expert SVG diagram designer for enterprise SAP technology proposals. When given a description, generate a complete, self-contained SVG diagram.

RULES
- Return ONLY the SVG element. Start with <svg and end with </svg>. No markdown fences, no explanation, no text outside the SVG.
- Use viewBox with explicit width and height. Default: width="900" height="560" for landscape diagrams, width="700" height="960" for tall/portrait ones.
- Dark background (#0E1020). All text must be legible on dark.
- Gradient bar at the very top (y=0, height=3): linear gradient left-to-right #FFB87E -> #FF7E51 -> #B88A99 -> #6399F0.
- Color palette: accent orange #FF7E51, blue #6399F0, peach #FFA962, green #00a864, mauve #B88A99, warm #FFB87E.
- Use these fills at 10-15% opacity for box backgrounds, full opacity for labels and accents.
- fontFamily="Inter, sans-serif" for all text. Bold weight for titles and layer labels.
- Include a small footer text at the bottom: "Confidential. Generated by DXC Proposal Builder." in rgba(255,255,255,0.2), font-size 9.
- Include the DXC logo SVG path top-right, scaled small (about 70px wide). The logo path data: M220.055 60.7583C252.905 60.7583 279.643 87.4387 279.644 120.247C279.644 153.055 252.905 179.735 220.055 179.735H61V155.455H220.055C239.522 155.455 255.362 139.657 255.362 120.247C255.362 100.836 239.522 85.0396 220.055 85.0396H61V60.7583H220.055ZM798 85.0386H638.945C619.478 85.0386 603.638 100.836 603.638 120.247C603.638 139.657 619.478 155.454 638.945 155.454H798V179.735H638.945C606.08 179.735 579.357 153.054 579.356 120.247C579.356 87.4387 606.095 60.7573 638.945 60.7573H798V85.0386ZM556.104 85.0386C530.11 85.0387 511.856 96.5366 492.531 108.706C486.261 112.662 479.906 116.647 473.278 120.204C479.905 123.76 486.261 127.744 492.531 131.701C511.856 143.87 530.11 155.368 556.104 155.368V179.649C523.097 179.649 499.987 165.095 479.591 152.254C462.637 141.585 447.997 132.358 430.058 132.358C412.118 132.358 397.478 141.571 380.524 152.254C360.128 165.095 337.018 179.649 304.011 179.649V155.368C330.006 155.368 348.259 143.87 367.584 131.701C373.854 127.744 380.211 123.76 386.838 120.204C380.211 116.647 373.854 112.662 367.584 108.706C348.259 96.5366 330.006 85.0386 304.011 85.0386V60.7573C337.018 60.7573 360.128 75.3119 380.524 88.1665C397.478 98.8358 412.118 108.063 430.058 108.063V108.048C447.997 108.048 462.637 98.8364 479.591 88.1528C499.987 75.3125 523.097 60.7575 556.104 60.7573V85.0386Z — use a radialGradient fill: stops #FFB87E at 0%, #FF7E51 at 55.8%, #6399F0 at 100%, gradientTransform matrix(402.422 -113.55 49.0928 173.987 432 120.032).
- Make the diagram genuinely useful and information-dense. Label everything clearly. Use boxes, arrows, zones, and hierarchy to convey structure.`

export async function POST(req: NextRequest) {
  const apiKey = req.headers.get('x-api-key')
  if (!apiKey) return NextResponse.json({ error: 'API key missing' }, { status: 401 })

  let body: { prompt: string }
  try { body = await req.json() } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }) }

  const { prompt } = body
  if (!prompt?.trim()) return NextResponse.json({ error: 'Prompt required' }, { status: 400 })

  const client = new Anthropic({ apiKey })

  try {
    const message = await client.messages.create({
      model: 'claude-sonnet-4-5',
      max_tokens: 4096,
      system: SYSTEM,
      messages: [{ role: 'user', content: prompt }],
    })

    const svg = message.content[0]?.type === 'text' ? message.content[0].text.trim() : ''
    return NextResponse.json({ svg })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Generation failed'
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
